-- Auryk Control · esquema repetible para Supabase PostgreSQL
-- Ejecutar como propietario del proyecto desde SQL Editor.
create extension if not exists pgcrypto;

do $$ begin create type public.content_status as enum ('draft','published','archived'); exception when duplicate_object then null; end $$;
do $$ begin create type public.admin_role as enum ('admin','editor'); exception when duplicate_object then null; end $$;

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path='' as $$begin new.updated_at=now();return new;end$$;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text not null,full_name text,role public.admin_role not null default 'editor',is_active boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists profiles_email_unique_idx on public.profiles(lower(email));
create table if not exists public.site_sections(id uuid primary key default gen_random_uuid(),key text not null unique,title text not null,description text,is_visible boolean not null default true,status public.content_status not null default 'draft',sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz,created_by uuid references auth.users(id),updated_by uuid references auth.users(id));
create table if not exists public.site_settings(id uuid primary key default gen_random_uuid(),key text not null unique,value text,is_public boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table if not exists public.home_content(id uuid primary key default gen_random_uuid(),eyebrow text,hero_title text not null,subtitle text,introduction text,story_slides jsonb not null default '[]',cta_label text,cta_url text,value_messages jsonb not null default '[]',capabilities jsonb not null default '[]',info_blocks jsonb not null default '[]',composition jsonb not null default '{}',is_visible boolean not null default true,status public.content_status not null default 'draft',sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz,created_by uuid references auth.users(id),updated_by uuid references auth.users(id));
create table if not exists public.management_modules(id uuid primary key default gen_random_uuid(),title text not null,slug text not null unique,short_description text,why_needed text,how_we_work text,client_receives text,image_url text,is_visible boolean not null default true,status public.content_status not null default 'draft',sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz,created_by uuid references auth.users(id),updated_by uuid references auth.users(id));
create table if not exists public.services(id uuid primary key default gen_random_uuid(),title text not null,slug text not null unique,short_description text,benefits text,includes text,image_url text,is_visible boolean not null default true,status public.content_status not null default 'draft',sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz,created_by uuid references auth.users(id),updated_by uuid references auth.users(id));
create table if not exists public.clients(id uuid primary key default gen_random_uuid(),internal_name text not null,normalized_name text generated always as (lower(regexp_replace(trim(internal_name),'\s+',' ','g'))) stored,public_name text,logo_url text,sector text,description text,publish_authorized boolean not null default false,is_visible boolean not null default false,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),unique(normalized_name));
create table if not exists public.projects(id uuid primary key default gen_random_uuid(),title text not null,slug text not null unique,discipline text,service text,sector text,client_id uuid references public.clients(id) on delete set null,client_internal_name text,show_client boolean not null default false,location text,project_date date,description text,problem text,solution text,result text,story text,scope text,benefits text,cta_label text,cta_url text,cover_image_url text,alt_text text,featured_home boolean not null default false,status public.content_status not null default 'draft',sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz,created_by uuid references auth.users(id),updated_by uuid references auth.users(id));
create table if not exists public.media_assets(id uuid primary key default gen_random_uuid(),title text not null,description text,alt_text text not null default '',category text,project_id uuid references public.projects(id) on delete set null,service_id uuid references public.services(id) on delete set null,storage_bucket text not null,storage_path text not null,public_url text,mime_type text not null,size_bytes bigint,focal_x numeric(5,2) not null default 50 check(focal_x between 0 and 100),focal_y numeric(5,2) not null default 50 check(focal_y between 0 and 100),usage_areas text[] not null default '{}',is_public boolean not null default false,status public.content_status not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),unique(storage_bucket,storage_path));
create table if not exists public.project_images(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,media_id uuid not null references public.media_assets(id) on delete restrict,image_type text not null default 'gallery' check(image_type in ('cover','gallery','process','before','after')),caption text,alt_text text,sort_order integer not null default 0,created_at timestamptz not null default now(),unique(project_id,media_id,image_type));
create table if not exists public.audit_log(id bigint generated always as identity primary key,user_id uuid references auth.users(id) on delete set null,action text not null,table_name text not null,record_id uuid,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin' and p.is_active)$$;
create or replace function public.is_staff() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','editor') and p.is_active)$$;

create index if not exists projects_public_idx on public.projects(status,sort_order,published_at desc);create index if not exists projects_featured_idx on public.projects(featured_home) where status='published';create index if not exists media_public_idx on public.media_assets(is_public,status,category);create index if not exists management_public_idx on public.management_modules(status,is_visible,sort_order);create index if not exists services_public_idx on public.services(status,is_visible,sort_order);create index if not exists project_images_order_idx on public.project_images(project_id,image_type,sort_order);

do $$ declare t text; begin foreach t in array array['profiles','site_sections','site_settings','home_content','management_modules','services','clients','projects','media_assets'] loop execute format('drop trigger if exists set_updated_at on public.%I',t);execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t);end loop;end$$;
create or replace function public.audit_changes() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.audit_log(user_id,action,table_name,record_id,old_data,new_data) values(auth.uid(),tg_op,tg_table_name,coalesce(new.id,old.id),case when tg_op in('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in('INSERT','UPDATE') then to_jsonb(new) end);return coalesce(new,old);end$$;
do $$ declare t text; begin foreach t in array array['site_sections','site_settings','home_content','management_modules','services','clients','projects','media_assets','project_images'] loop execute format('drop trigger if exists audit_changes on public.%I',t);execute format('create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.audit_changes()',t);end loop;end$$;

alter table public.profiles enable row level security;alter table public.site_sections enable row level security;alter table public.site_settings enable row level security;alter table public.home_content enable row level security;alter table public.management_modules enable row level security;alter table public.services enable row level security;alter table public.clients enable row level security;alter table public.projects enable row level security;alter table public.media_assets enable row level security;alter table public.project_images enable row level security;alter table public.audit_log enable row level security;

drop policy if exists profiles_self on public.profiles;create policy profiles_self on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists profiles_admin on public.profiles;create policy profiles_admin on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists public_sections on public.site_sections;create policy public_sections on public.site_sections for select to anon using(status='published' and is_visible);
drop policy if exists public_settings on public.site_settings;create policy public_settings on public.site_settings for select to anon using(is_public);
drop policy if exists public_home on public.home_content;create policy public_home on public.home_content for select to anon using(status='published' and is_visible);
drop policy if exists public_management on public.management_modules;create policy public_management on public.management_modules for select to anon using(status='published' and is_visible);
drop policy if exists public_services on public.services;create policy public_services on public.services for select to anon using(status='published' and is_visible);
drop policy if exists public_projects on public.projects;create policy public_projects on public.projects for select to anon using(status='published');
drop policy if exists public_clients on public.clients;create policy public_clients on public.clients for select to anon using(publish_authorized and is_visible);
drop policy if exists public_media on public.media_assets;create policy public_media on public.media_assets for select to anon using(status='published' and is_public and storage_bucket='public-media');
drop policy if exists public_project_images on public.project_images;create policy public_project_images on public.project_images for select to anon using(exists(select 1 from public.projects p where p.id=project_id and p.status='published') and exists(select 1 from public.media_assets m where m.id=media_id and m.status='published' and m.is_public));
revoke select on public.clients from anon;grant select(id,public_name,logo_url,sector,description,sort_order) on public.clients to anon;
revoke select on public.projects from anon;grant select(id,title,slug,discipline,service,sector,location,project_date,description,problem,solution,result,story,scope,benefits,cta_label,cta_url,cover_image_url,alt_text,featured_home,status,sort_order,published_at) on public.projects to anon;
do $$ declare t text; begin foreach t in array array['site_sections','site_settings','home_content','management_modules','services','clients','projects','media_assets','project_images'] loop execute format('drop policy if exists staff_crud on public.%I',t);execute format('create policy staff_crud on public.%I for all to authenticated using(public.is_staff()) with check(public.is_staff())',t);end loop;end$$;
drop policy if exists audit_admin_read on public.audit_log;create policy audit_admin_read on public.audit_log for select to authenticated using(public.is_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('public-media','public-media',true,12582912,array['image/webp','image/jpeg','image/png']),('private-media','private-media',false,12582912,array['image/webp','image/jpeg','image/png']) on conflict(id) do update set file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists storage_public_read on storage.objects;create policy storage_public_read on storage.objects for select to anon using(bucket_id='public-media');
drop policy if exists storage_staff_read on storage.objects;create policy storage_staff_read on storage.objects for select to authenticated using(public.is_staff());
drop policy if exists storage_admin_insert on storage.objects;create policy storage_admin_insert on storage.objects for insert to authenticated with check(public.is_admin() and bucket_id in('public-media','private-media'));
drop policy if exists storage_admin_update on storage.objects;create policy storage_admin_update on storage.objects for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists storage_admin_delete on storage.objects;create policy storage_admin_delete on storage.objects for delete to authenticated using(public.is_admin());

insert into public.site_sections(key,title,status,sort_order) values('home','Inicio','published',10),('management','Gestión','published',20),('services','Servicios','published',30),('projects','Proyectos','published',40),('clients','Clientes','draft',50) on conflict(key) do nothing;
insert into public.site_settings(key,value,is_public) values('meta_title','Auryk Holding Group | Gestión. Dirección. Resultados.',true),('meta_description','Una sola dirección para convertir proyectos complejos en resultados listos para operar.',true),('phone','+18495137961',true),('email','info@aurykholdingroup.com',true),('instagram','https://www.instagram.com/auryk_holdingroup/',true) on conflict(key) do nothing;

-- Primer administrador (después de crear el usuario en Authentication > Users):
-- insert into public.profiles(id,email,full_name,role,is_active)
-- select id,email,'Administrador Auryk','admin',true from auth.users where email='ADMIN@EJEMPLO.COM'
-- on conflict(id) do update set role='admin',is_active=true;
