(function () {
  "use strict";
  const api = window.AurykAPI;
  const $ = s => document.querySelector(s);
  const auth = $("#authView"), app = $("#appView"), editor = $("#editorView"), mediaView = $("#mediaView");
  let current = "dashboard", records = [], editingId = null, busy = false;
  const schemas = {
    home:{table:"home_content",title:"Inicio",fields:[["eyebrow","Etiqueta"],["hero_title","Título principal","textarea"],["subtitle","Subtítulo","textarea"],["introduction","Introducción","textarea"],["cta_label","Texto CTA"],["cta_url","Destino CTA"],["composition","Composición visual","textarea"],["status","Estado","status"],["sort_order","Orden","number"],["is_visible","Visible","checkbox"]]},
    management:{table:"management_modules",title:"Gestión",fields:[["title","Título"],["slug","Slug"],["short_description","Descripción breve","textarea"],["why_needed","Por qué lo necesita","textarea"],["how_we_work","Cómo lo hacemos","textarea"],["client_receives","Qué recibe","textarea"],["image_url","Imagen"],["status","Estado","status"],["sort_order","Orden","number"],["is_visible","Visible","checkbox"]]},
    projects:{table:"projects",title:"Proyectos",fields:[["title","Título"],["slug","Slug"],["discipline","Disciplina"],["service","Servicio"],["sector","Sector"],["client_internal_name","Cliente interno"],["show_client","Mostrar cliente","checkbox"],["location","Ubicación"],["description","Descripción","textarea"],["problem","Problema","textarea"],["solution","Solución","textarea"],["result","Resultado","textarea"],["story","Historia","textarea"],["scope","Alcance","textarea"],["benefits","Beneficios","textarea"],["cover_image_url","Portada"],["featured_home","Destacado en Inicio","checkbox"],["status","Estado","status"],["sort_order","Orden","number"]]},
    services:{table:"services",title:"Servicios",fields:[["title","Título"],["slug","Slug"],["short_description","Descripción","textarea"],["benefits","Beneficios","textarea"],["includes","Qué incluye","textarea"],["image_url","Imagen"],["status","Estado","status"],["sort_order","Orden","number"],["is_visible","Visible","checkbox"]]},
    clients:{table:"clients",title:"Clientes",fields:[["internal_name","Nombre interno"],["public_name","Nombre público"],["sector","Sector"],["description","Descripción","textarea"],["logo_url","Logotipo"],["publish_authorized","Autorización para publicar","checkbox"],["is_visible","Visible","checkbox"],["sort_order","Orden","number"]]},
    settings:{table:"site_settings",title:"Configuración",fields:[["key","Clave"],["value","Valor","textarea"],["is_public","Público","checkbox"]]}
  };
  function toast(message, error=false){const t=$("#toast");t.textContent=message;t.className=`toast show${error?" error":""}`;setTimeout(()=>t.className="toast",3200)}
  function setBusy(value){busy=value;document.querySelectorAll("button").forEach(b=>b.disabled=value);}
  function field([name,label,type="text"], value={}){
    if(type==="checkbox") return `<label class="field"><span>${label}</span><input name="${name}" type="checkbox" ${value[name]!==false?"checked":""}></label>`;
    if(type==="status") return `<label class="field"><span>${label}</span><select name="${name}"><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label>`;
    const full=type==="textarea"?" full":""; return `<label class="field${full}"><span>${label}</span>${type==="textarea"?`<textarea name="${name}" rows="4"></textarea>`:`<input name="${name}" type="${type}" ${type==="number"?'min="0"':''}>`}</label>`;
  }
  function normalizeStatus(v){return ({borrador:"draft",publicado:"published",archivado:"archived"})[v]||v||"draft"}
  function localStatus(v){return ({draft:"borrador",published:"publicado",archived:"archivado"})[v]||v||"borrador"}
  function showAuth(){auth.hidden=false;app.hidden=true;$("#configNotice").textContent=api.configured?"":"Configura config.js para conectar Supabase."}
  async function enter(){
    if(!api.configured||!api.session){showAuth();return} setBusy(true);
    try{await api.user();if(!(await api.isAdmin()))throw new Error("Esta cuenta no tiene permisos administrativos.");auth.hidden=true;app.hidden=false;await showView("dashboard")}
    catch(e){api.signOut();showAuth();toast(e.message,true)}finally{setBusy(false)}
  }
  async function showView(view){
    current=view;document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));
    if(view==="dashboard"){$("#dashboardView").classList.add("active");$("#viewTitle").textContent="Resumen";await dashboard();return}
    if(view==="media"){mediaView.classList.add("active");$("#viewTitle").textContent="Fotografías";await loadMedia();return}
    editor.classList.add("active");$("#viewTitle").textContent=schemas[view].title;await loadRecords();
  }
  async function dashboard(){
    try{const [p,c,m,a]=await Promise.all([api.select("projects","select=id,status"),api.select("clients","select=id"),api.select("media_assets","select=id"),api.select("audit_log","select=action,table_name,created_at&order=created_at.desc&limit=8")]);
      const cards=[["Proyectos publicados",p.filter(x=>x.status==="published").length],["Proyectos en borrador",p.filter(x=>x.status==="draft").length],["Clientes",c.length],["Fotografías",m.length]];
      $("#stats").innerHTML=cards.map(x=>`<article class="stat"><span>${x[0]}</span><b>${x[1]}</b></article>`).join("");$("#activity").innerHTML=a.length?a.map(x=>`<div class="activity-item"><b>${x.action}</b><span>${x.table_name}</span><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join(""):"<p>Sin actividad registrada.</p>";
    }catch(e){toast(e.message,true)}
  }
  async function loadRecords(){const s=schemas[current];try{records=await api.select(s.table,"select=*&order=sort_order.asc.nullslast,updated_at.desc");renderRecords()}catch(e){toast(e.message,true)}}
  function renderRecords(){const q=$("#search").value.toLowerCase(),st=normalizeStatus($("#statusFilter").value);const visible=records.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!st||x.status===st));$("#records").innerHTML=visible.length?visible.map(x=>`<article class="record" data-id="${x.id}"><div><b>${x.title||x.hero_title||x.public_name||x.internal_name||x.key||"Sin título"}</b><small>${x.slug||x.sector||x.updated_at?.slice(0,10)||""}</small></div>${x.status?`<span class="badge ${localStatus(x.status)}">${localStatus(x.status)}</span>`:""}</article>`).join(""):"<div class='panel'>No hay registros.</div>"}
  function openForm(item={}){const s=schemas[current];editingId=item.id||null;const f=$("#recordForm");f.hidden=false;f.innerHTML=s.fields.map(x=>field(x,item)).join("")+`<div class="editor-actions"><button class="primary" type="submit">Guardar</button><button id="preview" type="button">Vista previa</button>${editingId?'<button id="duplicate" type="button">Duplicar</button><button id="delete" class="danger" type="button">Eliminar</button>':''}</div>`;
    s.fields.forEach(([name,,type])=>{const el=f.elements[name];if(!el)return;if(type==="checkbox")el.checked=item[name]===true;else el.value=type==="status"?normalizeStatus(item[name]):item[name]??""});
  }
  function formValue(){const s=schemas[current],f=$("#recordForm"),out={};s.fields.forEach(([name,,type])=>{const el=f.elements[name];out[name]=type==="checkbox"?el.checked:type==="number"?(el.value?Number(el.value):0):type==="status"?normalizeStatus(el.value):el.value.trim()});return out}
  async function save(e){e.preventDefault();if(busy)return;setBusy(true);try{const payload=formValue();if(payload.slug)payload.slug=payload.slug.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(editingId)await api.update(schemas[current].table,editingId,payload);else await api.insert(schemas[current].table,payload);toast("Cambios guardados.");$("#recordForm").hidden=true;await loadRecords()}catch(err){toast(err.message,true)}finally{setBusy(false)}}
  async function del(){if(!editingId||!confirm("Esta acción no se puede deshacer. ¿Eliminar el registro?"))return;try{await api.remove(schemas[current].table,editingId);toast("Registro eliminado.");$("#recordForm").hidden=true;await loadRecords()}catch(e){toast(e.message,true)}}
  async function duplicate(){const data=formValue();delete data.id;if(data.title)data.title+= " (copia)";if(data.slug)data.slug+=`-copia-${Date.now().toString().slice(-5)}`;data.status="draft";try{await api.insert(schemas[current].table,data);toast("Borrador duplicado.");await loadRecords()}catch(e){toast(e.message,true)}}
  function preview(){const d=$("#previewDialog");d.querySelector("iframe").src=`../index.html?preview=${encodeURIComponent(current)}&id=${editingId||"new"}`;d.showModal()}
  function imageToWebP(file,max=2200,quality=.84){return new Promise((resolve,reject)=>{if(!/^image\/(jpeg|png|webp)$/.test(file.type))return reject(new Error("Formato no permitido."));const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(url);b?resolve(b):reject(new Error("No se pudo optimizar la imagen."))},"image/webp",quality)};img.onerror=()=>reject(new Error("Imagen inválida."));img.src=url})}
  async function handleFiles(files){if(busy)return;setBusy(true);try{for(const file of files){const blob=await imageToWebP(file),safe=(file.name.replace(/\.[^.]+$/,"").replace(/[^a-z0-9_-]+/gi,"-")+"-"+crypto.randomUUID()+".webp").toLowerCase(),path=`library/${new Date().toISOString().slice(0,10)}/${safe}`;await api.upload(api.config.publicMediaBucket||"public-media",path,blob,"image/webp");await api.insert("media_assets",{title:file.name.replace(/\.[^.]+$/,"").slice(0,150),alt_text:"",storage_bucket:api.config.publicMediaBucket||"public-media",storage_path:path,public_url:api.publicUrl(api.config.publicMediaBucket||"public-media",path),mime_type:"image/webp",size_bytes:blob.size,status:"published",is_public:true})}toast("Fotografías optimizadas y subidas.");await loadMedia()}catch(e){toast(e.message,true)}finally{setBusy(false)}}
  async function loadMedia(){try{const q=$("#mediaSearch").value.toLowerCase(),m=await api.select("media_assets","select=*&order=created_at.desc&limit=200");$("#mediaGrid").innerHTML=m.filter(x=>!q||`${x.title} ${x.alt_text} ${x.category}`.toLowerCase().includes(q)).map(x=>`<article class="media-card"><img src="${x.public_url||""}" alt="${x.alt_text||""}" loading="lazy" style="object-position:${x.focal_x||50}% ${x.focal_y||50}%"><div><b>${x.title||"Sin título"}</b><small>${x.category||"Corporativa"}</small></div></article>`).join("")}catch(e){toast(e.message,true)}}
  $("#loginForm").addEventListener("submit",async e=>{e.preventDefault();setBusy(true);try{await api.signIn(e.currentTarget.email.value,e.currentTarget.password.value);await enter()}catch(err){toast(err.message,true)}finally{setBusy(false)}});
  $("#resetPassword").onclick=async()=>{const email=$("#loginForm").email.value;if(!email)return toast("Escribe tu correo primero.",true);try{await api.resetPassword(email,location.href);toast("Revisa tu correo.")}catch(e){toast(e.message,true)}};
  $("#logout").onclick=()=>{api.signOut();showAuth()};$("#nav").onclick=e=>{const b=e.target.closest("button[data-view]");if(b)showView(b.dataset.view)};$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");
  $("#newItem").onclick=()=>openForm({status:"draft",sort_order:0,is_visible:true});$("#refresh").onclick=loadRecords;$("#records").onclick=e=>{const r=e.target.closest(".record");if(r)openForm(records.find(x=>x.id===r.dataset.id))};$("#recordForm").onsubmit=save;$("#recordForm").onclick=e=>{if(e.target.id==="delete")del();if(e.target.id==="duplicate")duplicate();if(e.target.id==="preview")preview()};
  $("#search").oninput=renderRecords;$("#statusFilter").onchange=renderRecords;$("#uploadMedia").onclick=()=>$("#mediaInput").click();$("#mediaInput").onchange=e=>handleFiles(e.target.files);$("#mediaSearch").oninput=loadMedia;
  const dz=$("#dropzone");["dragenter","dragover"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add("drag")}));["dragleave","drop"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove("drag")}));dz.addEventListener("drop",e=>handleFiles(e.dataTransfer.files));
  $(".dialog-close").onclick=()=>$("#previewDialog").close();window.addEventListener("offline",()=>{$("#connectionText").textContent="Sin conexión";toast("Sin conexión. Conserva esta pantalla hasta recuperar internet.",true)});window.addEventListener("online",()=>{$("#connectionText").textContent="En línea"});
  if(api?.session)api.refresh().finally(enter);else showAuth();
})();
